# Generated by Django 4.2.3 on 2023-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valerii_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='age',
            field=models.PositiveBigIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.TextField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='skill',
            field=models.TextField(default=31),
            preserve_default=False,
        ),
    ]
